// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTab(arg1) {
  return window['go']['main']['App']['DeleteTab'](arg1);
}

export function GetLabelList() {
  return window['go']['main']['App']['GetLabelList']();
}

export function GetTabList() {
  return window['go']['main']['App']['GetTabList']();
}

export function SaveLabel(arg1) {
  return window['go']['main']['App']['SaveLabel'](arg1);
}

export function UpdateTab(arg1) {
  return window['go']['main']['App']['UpdateTab'](arg1);
}
