// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTab(arg1) {
  return window['go']['main']['App']['DeleteTab'](arg1);
}

export function GetLabelList() {
  return window['go']['main']['App']['GetLabelList']();
}

export function GetTab(arg1) {
  return window['go']['main']['App']['GetTab'](arg1);
}

export function GetTabLabelList(arg1) {
  return window['go']['main']['App']['GetTabLabelList'](arg1);
}

export function GetTabList(arg1) {
  return window['go']['main']['App']['GetTabList'](arg1);
}

export function SaveLabel(arg1) {
  return window['go']['main']['App']['SaveLabel'](arg1);
}

export function ToPDF(arg1) {
  return window['go']['main']['App']['ToPDF'](arg1);
}

export function UpdateTab(arg1) {
  return window['go']['main']['App']['UpdateTab'](arg1);
}
