// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetTabList():Promise<main.H>;

export function Greet(arg1:string):Promise<string>;

export function UpdateTab(arg1:string):Promise<main.H>;
