// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateToPDFTask(arg1:string):Promise<main.H>;

export function DeleteTab(arg1:string):Promise<main.H>;

export function GetConfigList():Promise<main.H>;

export function GetLabelList():Promise<main.H>;

export function GetTab(arg1:number):Promise<main.H>;

export function GetTabLabelList(arg1:number):Promise<main.H>;

export function GetTabList(arg1:number):Promise<main.H>;

export function SaveConfig(arg1:string):Promise<main.H>;

export function SaveLabel(arg1:string):Promise<main.H>;

export function UpdateTab(arg1:string):Promise<main.H>;
